apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  creationTimestamp: null
  name: podinfo
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: podinfo
          servicePort: 9898
        path: /podinfo
      - backend:
          serviceName: metricsinfo
          servicePort: 3000
        path: /mighty-fine
status:
  loadBalancer: {}
